name: enigmatech
description: Secure file encryption web app with premium UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  universal_html: ^2.2.1
  url_launcher: ^6.1.7
  flutter_dotenv: ^5.0.2
  encrypt: ^5.0.1
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - .env

web:  # <-- REMOVE THE 2 SPACE INDENT HERE
  runtime: release
  builders:
    universal_html:
      generate_for: ['web/**']